kind: Template
apiVersion: v1
metadata:
  name: ${NAME}${SUFFIX}-deployment-template
objects:

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      webhook-url: ${WEBHOOK_URL}

      target-email: ${FEEDBACK_TARGET_EMAIL}
      smtp-host: ${SMTP_SERVER_ADDRESS}
      
      ${JC_INTERFACE_USERNAME}: ${JC_INTERFACE_USERNAME}
      ${JC_INTERFACE_PROD_PASSWORD}: ${JC_INTERFACE_PROD_PASSWORD}
      ${JC_INTERFACE_TEST_PASSWORD}: ${JC_INTERFACE_TEST_PASSWORD}
      ${JC_INTERFACE_DEV_PASSWORD}: ${JC_INTERFACE_DEV_PASSWORD}

      ${WSGW_URL_PROD}: ${WSGW_URL_PROD}
      ${WSGW_URL_TEST}: ${WSGW_URL_TEST}
      ${WSGW_URL_DEV}: ${WSGW_URL_DEV}
      ${CATS_URL_PROD}: ${CATS_URL_PROD}
      ${CATS_URL_TEST}: ${CATS_URL_TEST}
      ${CATS_URL_DEV}: ${CATS_URL_DEV}

      ${REQUEST_AGENCY_IDENTIFIER_ID_PROD}: ${REQUEST_AGENCY_IDENTIFIER_ID_PROD}
      ${REQUEST_AGENCY_IDENTIFIER_ID_TEST}: ${REQUEST_AGENCY_IDENTIFIER_ID_TEST}
      ${REQUEST_AGENCY_IDENTIFIER_ID_DEV}: ${REQUEST_AGENCY_IDENTIFIER_ID_DEV}
      ${REQUEST_PART_ID_PROD}: ${REQUEST_PART_ID_PROD}
      ${REQUEST_PART_ID_TEST}: ${REQUEST_PART_ID_TEST}
      ${REQUEST_PART_ID_DEV}: ${REQUEST_PART_ID_DEV}
      ${PCSS_APPLICATION_CODE}: ${PCSS_APPLICATION_CODE}
      ${SCV_APPLICATION_CODE}: ${SCV_APPLICATION_CODE}

      ${TARGET_URL}: ${TARGET_URL}
      ${COOKIE}: ${COOKIE}
    type: Opaque

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          volumes:
            - name: ${NAME}${SUFFIX}-config-volume
              configMap:
                name: ${CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${CONFIG_FILE_NAME}
                    path: ${CONFIG_FILE_NAME}
          containers:
            - name: ${NAME}${SUFFIX}
              command:
                - /bin/bash
                - -c
                - "./run.sh"
              image: ""
              ports: []
              env:
                - name: JC_INTERFACE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${JC_INTERFACE_USERNAME}

                - name: JC_INTERFACE_PROD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${JC_INTERFACE_PROD_PASSWORD}

                - name: JC_INTERFACE_TEST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${JC_INTERFACE_TEST_PASSWORD}

                - name: JC_INTERFACE_DEV_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${JC_INTERFACE_DEV_PASSWORD}

                - name: WSGW_URL_PROD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${WSGW_URL_PROD}

                - name: WSGW_URL_TEST 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${WSGW_URL_TEST}

                - name: WSGW_URL_DEV 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${WSGW_URL_DEV}

                - name: CATS_URL_PROD 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${CATS_URL_PROD}

                - name: CATS_URL_TEST 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${CATS_URL_TEST}

                - name: CATS_URL_DEV 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${CATS_URL_DEV}

                - name: REQUEST_AGENCY_IDENTIFIER_ID_PROD 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${REQUEST_AGENCY_IDENTIFIER_ID_PROD}

                - name: REQUEST_AGENCY_IDENTIFIER_ID_TEST 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${REQUEST_AGENCY_IDENTIFIER_ID_TEST}

                - name: REQUEST_AGENCY_IDENTIFIER_ID_DEV 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${REQUEST_AGENCY_IDENTIFIER_ID_DEV}

                - name: REQUEST_PART_ID_PROD 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${REQUEST_PART_ID_PROD}

                - name: REQUEST_PART_ID_TEST 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${REQUEST_PART_ID_TEST}

                - name: REQUEST_PART_ID_DEV 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${REQUEST_PART_ID_DEV}

                - name: PCSS_APPLICATION_CODE 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${PCSS_APPLICATION_CODE}
                  
                - name: SCV_APPLICATION_CODE 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${SCV_APPLICATION_CODE}

                - name: TARGET_URL 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${TARGET_URL}

                - name: COOKIE 
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: ${COOKIE}

                - name: WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: webhook-url
                - name: WEBHOOK_LEVEL
                  value: ${WEBHOOK_LEVEL}
                - name: FRIENDLY_PROJECT_NAME
                  value: ${ENVIRONMENT_FRIENDLY_NAME}
                - name: PROJECT_NAME
                  value: ${ENVIRONMENT_NAME}

                - name: FEEDBACK_TARGET_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: target-email
                - name: SMTP_SERVER_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: smtp-host
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: ${NAME}${SUFFIX}-config-volume
                  mountPath: ${CONFIG_MOUNT_PATH}${CONFIG_FILE_NAME}
                  subPath: ${CONFIG_FILE_NAME}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
    value: test
  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: test
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value:
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: Test
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: Test
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: test
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    description: The namespace of the OpenShift project containing the imagestream for the application.
    required: true
    value: ca7f8f-tools
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: dev

  - name: USE_CSV
    displayName: USE_CSV
    description: USE_CSV
    required: true
    value: "false"

  - name: REQUEUE_WRONG_BN_CORPS
    displayName: Requeue Wrong Business Number Corps
    description: Automatically requeue Corps that have a business number mismatch.
    required: true
    value: "false"

  - name: JC_INTERFACE_USERNAME
    displayName: JC_INTERFACE_USERNAME
    description: JC_INTERFACE_USERNAME
    required: true
    value: jc-interface-username

  - name: JC_INTERFACE_PROD_PASSWORD
    displayName: JC_INTERFACE_PROD_PASSWORD
    description: JC_INTERFACE_PROD_PASSWORD
    required: true
    value: jc-interface-prod-password

  - name: JC_INTERFACE_TEST_PASSWORD
    displayName: JC_INTERFACE_TEST_PASSWORD
    description: JC_INTERFACE_TEST_PASSWORD
    required: true
    value: jc-interface-test-password

  - name: JC_INTERFACE_DEV_PASSWORD
    displayName: JC_INTERFACE_DEV_PASSWORD
    description: JC_INTERFACE_DEV_PASSWORD
    required: true
    value: jc-interface-dev-password

  - name: WSGW_URL_PROD
    displayName: WSGW_URL_PROD
    description: WSGW_URL_PROD
    required: true
    value: wsgw-url-prod

  - name: WSGW_URL_TEST
    displayName: WSGW_URL_TEST
    description: WSGW_URL_TEST
    required: true
    value: wsgw-url-test

  - name: WSGW_URL_DEV
    displayName: WSGW_URL_DEV
    description: WSGW_URL_DEV
    required: true
    value: wsgw-url-dev

  - name: CATS_URL_PROD
    displayName: CATS_URL_PROD
    description: CATS_URL_PROD
    required: true
    value: cats-url-prod

  - name: CATS_URL_TEST
    displayName: CATS_URL_TEST
    description: CATS_URL_TEST
    required: true
    value: cats-url-test

  - name: CATS_URL_DEV
    displayName: CATS_URL_DEV
    description: CATS_URL_DEV
    required: true
    value: cats-url-dev

  - name: REQUEST_AGENCY_IDENTIFIER_ID_PROD
    displayName: REQUEST_AGENCY_IDENTIFIER_ID_PROD
    description: REQUEST_AGENCY_IDENTIFIER_ID_PROD
    required: true
    value: request-agency-identifier-id-prod

  - name: REQUEST_AGENCY_IDENTIFIER_ID_TEST
    displayName: REQUEST_AGENCY_IDENTIFIER_ID_TEST
    description: REQUEST_AGENCY_IDENTIFIER_ID_TEST
    required: true
    value: request-agency-identifier-id-test

  - name: REQUEST_AGENCY_IDENTIFIER_ID_DEV
    displayName: REQUEST_AGENCY_IDENTIFIER_ID_DEV
    description: REQUEST_AGENCY_IDENTIFIER_ID_DEV
    required: true
    value: request-agency-identifier-id-dev

  - name: REQUEST_PART_ID_PROD
    displayName: REQUEST_PART_ID_PROD
    description: REQUEST_PART_ID_PROD
    required: true
    value: requst-part-id-prod

  - name: REQUEST_PART_ID_TEST
    displayName: REQUEST_PART_ID_TEST
    description: REQUEST_PART_ID_TEST
    required: true
    value: request-part-id-test

  - name: REQUEST_PART_ID_DEV
    displayName: REQUEST_PART_ID_DEV
    description: REQUEST_PART_ID_DEV
    required: true
    value: request-part-id-dev

  - name: PCSS_APPLICATION_CODE
    displayName: PCSS_APPLICATION_CODE
    description: PCSS_APPLICATION_CODE
    required: true
    value: pcss-application-code

  - name: SCV_APPLICATION_CODE
    displayName: SCV_APPLICATION_CODE
    description: SCV_APPLICATION_CODE
    required: true
    value: scv-application-code

  - name: TARGET_URL
    displayName: TARGET_URL
    description: TARGET_URL
    required: true
    value: target-url

  - name: COOKIE
    displayName: COOKIE
    description: COOKIE
    required: true
    value: cookie

  - name: WEBHOOK_URL
    displayName: Webhook URL
    description: The URL of the webhook to use for notifications.  If not specified, the webhook integration feature is disabled.
    required: false
    value: ""
  - name: WEBHOOK_LEVEL
    displayName: Webhook Log Level
    description: The webhook log level filter; 0=Error, 1=Warning, 2=Info
    required: false
    value: "2"

  - name: ENVIRONMENT_FRIENDLY_NAME
    displayName: Friendly Environment Name
    description: The human readable name of the environment.  This variable is used by the webhook integration to identify the environment in which the backup notifications originate.
    required: false
    value: ""
  - name: ENVIRONMENT_NAME
    displayName: Environment Name (Environment Id)
    description: The name or Id of the environment.  This variable is used by the webhook integration to identify the environment in which the backup notifications originate.
    required: false
    value: ""

  - name: FEEDBACK_TARGET_EMAIL
    displayName: Feedback Target Url
    description: The email address to which the feedback is to be delivered.
    required: false
    value: ""
  - name: SMTP_SERVER_ADDRESS
    displayName: SMTP Server Address
    description: The SMTP server address used for sending email.
    required: false
    value: ""

  - name: CONFIG_FILE_NAME
    displayName: Config File Name
    description: The name of the configuration file.
    required: true
    value: test.conf
  - name: CONFIG_MAP_NAME
    displayName: Config Map Name
    description: The name of the configuration map.
    required: true
    value: test-conf
  - name: CONFIG_MOUNT_PATH
    displayName: Config Mount Path
    description: The path to use to mount the config file.
    required: true
    value: /opt/app-root/src/

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: "0"
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "0"
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 0Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 0Mi
